### ISSUE TITLE
dont patch globals

### ISSUE THREAD

**Issue by Raynos** [YuzuJS/setImmediate#16]
`var setImmediate = require("setImmediate")`

It should be a clean function without global side effects.

Have side effects be opt in.

**Comment by ibc** [comment]
@domenic for those of us coding "widgets" to be plugged in 3rd party websites, including code into the widget that pollutes the `window` namespace is a **MUST NOT** since it may create conflicts with the hosting website (not in our control).

> The CommonJS module is just a transport format for those who don't have the ability to load scripts directly into their environment.

Well, do you really think that developers using CommonJS use it because "they don't have the ability to load scripts directly into their environment"?

**Comment by domenic** [comment]
It sounds like this library isn't a good fit for your requirements then.

**Comment by ibc** [comment]
Developers coding with CommonJS/AMD in mind produce code/libraries suitable for CommonJS and AMD, and also for all those devs still loading scripts via `<script>` tags. That's easy by simply using `browserify` (or similar) which produces CommonJS/AMD/global suitable exports or by just adding these few lines of code:

```js
// AMD
if ( typeof define == 'function' && define.amd )
{
  define([], function()
  {
    return
    {
      setImmediate   : setImmediate,
      clearImmediate : clearImmediate,
      toGlobal       : toGlobal
    };
  });
}
// CommonJS
else if ( typeof module != 'undefined' && module.exports )
{
	exports.setImmediate = setImmediate;
  exports.clearImmediate = clearImmediate;
}
// Legacy <script> loading
else
{
	global.setImmediate = setImmediate;
	global.clearImmediate = clearImmediate;
}
```

The problem is in the other side: in all those libraries forcing global pollution yes or yes and arguing that it 's the desired design. Just the wrong way.

**Comment by ibc** [comment]
> It sounds like this library isn't a good fit for your requirements then.

Yes, the feature provided by this library fits my requirements. The problem is the way in which you force me to consume the library. Hope you see the difference.

**Comment by domenic** [comment]
I was referring to the library as a whole, not just its features.

**Comment by ibc** [comment]
IMHO you should not force a single way of consuming your library (or the good features it provides).

**Comment by domenic** [comment]
I understand, respect, and disagree with your opinion.

**Comment by zloirock** [comment]
If you don't need global pollutions - you can use `library` version of `core-js`
```js
var setImmediate = require('core-js/library/fn/set-immediate');
```
IIRC the same approaches for task implementation.

**Comment by ibc** [comment]
Thanks @zloirock, will check it.

**Comment by ForbesLindesay** [comment]
For most use cases, you'd be better off with https://www.npmjs.com/package/asap than a setImmediate polyfill anyway.
